import wx,os
class StartWindow(wx.Frame):

	def __init__(self, *args, **kw):
		super(StartWindow, self).__init__(*args, **kw)
		self.panel = wx.Panel(self)
		self.main_boxsizer = wx.BoxSizer(wx.VERTICAL)
		self.name_font = wx.Font(36, wx.DECORATIVE, wx.ITALIC, wx.BOLD)
		self.text_font = wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.NORMAL)
		self.hello_world_statictext = wx.StaticText(self.panel, wx.ID_ANY, 'StatHelper')
		self.hello_world_statictext.SetFont(self.name_font)
		self.select_file_boxsizer = wx.BoxSizer(wx.HORIZONTAL)
		self.select_file_statictext = wx.StaticText(self.panel, wx.ID_ANY, 'Select a file')
		self.select_file_statictext.SetFont(self.text_font)
		self.select_file_filepickerctrl = wx.FilePickerCtrl(self.panel, wx.ID_ANY, '', 'Select a file', '*.csv', wx.DefaultPosition, wx.Size(210,21))
		self.select_file_boxsizer.Add(self.select_file_statictext,0,wx.CENTER)
		self.select_file_boxsizer.AddSpacer(5)
		self.select_file_boxsizer.Add(self.select_file_filepickerctrl,0,wx.CENTER)
		self.specify_sampling_flexgridsizer = wx.FlexGridSizer(3,3,5,5)
		self.row_statictext = wx.StaticText(self.panel, wx.ID_ANY, 'Row')
		self.row_statictext.SetFont(self.text_font)
		self.column_statictext = wx.StaticText(self.panel, wx.ID_ANY, 'Column')
		self.column_statictext.SetFont(self.text_font)
		self.specify_start_statictext = wx.StaticText(self.panel, wx.ID_ANY, 'Specify the start')
		self.specify_start_statictext.SetFont(self.text_font)
		self.specify_start_row = wx.SpinCtrl(self.panel, wx.ID_ANY, '0', wx.DefaultPosition, wx.Size(85,21))
		self.specify_start_row.SetRange(0,999999)
		self.specify_start_column = wx.SpinCtrl(self.panel, wx.ID_ANY, '0', wx.DefaultPosition, wx.Size(85,21))
		self.specify_start_column.SetRange(0,999999)
		self.specify_end_statictext = wx.StaticText(self.panel, wx.ID_ANY, 'Specify the end')
		self.specify_end_statictext.SetFont(self.text_font)
		self.specify_end_row = wx.SpinCtrl(self.panel, wx.ID_ANY, '0', wx.DefaultPosition, wx.Size(85,21))
		self.specify_end_row.SetRange(0,999999)
		self.specify_end_column = wx.SpinCtrl(self.panel, wx.ID_ANY, '0', wx.DefaultPosition, wx.Size(85,21))
		self.specify_end_column.SetRange(0,999999)
		self.specify_sampling_flexgridsizer.AddSpacer(0)
		self.specify_sampling_flexgridsizer.Add(self.row_statictext)
		self.specify_sampling_flexgridsizer.Add(self.column_statictext)
		self.specify_sampling_flexgridsizer.Add(self.specify_start_statictext)
		self.specify_sampling_flexgridsizer.Add(self.specify_start_row)
		self.specify_sampling_flexgridsizer.Add(self.specify_start_column)
		self.specify_sampling_flexgridsizer.Add(self.specify_end_statictext)
		self.specify_sampling_flexgridsizer.Add(self.specify_end_row)
		self.specify_sampling_flexgridsizer.Add(self.specify_end_column)
		self.show_statistics_button = wx.Button(self.panel, wx.ID_ANY, 'Show Statistics', wx.DefaultPosition, wx.Size(290,30))
		self.main_boxsizer.Add(self.hello_world_statictext,0,wx.CENTER+wx.ALL,5)
		self.main_boxsizer.Add(self.select_file_boxsizer,0,wx.CENTER+wx.ALL,5)
		self.main_boxsizer.Add(self.specify_sampling_flexgridsizer,0,wx.CENTER+wx.ALL,5)
		self.main_boxsizer.Add(self.show_statistics_button,0,wx.CENTER+wx.ALL,5)
		self.panel.SetSizer(self.main_boxsizer)
		self.SetMinSize(wx.Size(300,300))
		self.SetMaxSize(wx.Size(300,300))
		self.SetIcon(wx.Icon(os.path.abspath(os.curdir)+'/Images/favicon.ico'))